version: '3.8'

services:
  # Cassandra - Primary persistence layer
  cassandra:
    image: cassandra:4.1.3
    container_name: temporal-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=temporal
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=128
      - MAX_HEAP_SIZE=16G
      - HEAP_NEWSIZE=4G
    volumes:
      - cassandra-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 20G
        reservations:
          cpus: '6'
          memory: 18G
    networks:
      - temporal-network

  # Elasticsearch - Visibility store
  elasticsearch:
    image: elasticsearch:8.11.3
    container_name: temporal-elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms12g -Xmx12g
      - xpack.security.enabled=false
      - cluster.name=temporal-es-cluster
      - bootstrap.memory_lock=true
      - indices.memory.index_buffer_size=40%
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 16G
        reservations:
          cpus: '4'
          memory: 14G
    networks:
      - temporal-network

  # Temporal Admin Tools (for schema setup)
  temporal-admin-tools:
    image: temporalio/admin-tools:1.24.2
    container_name: temporal-admin-tools
    depends_on:
      cassandra:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=temporal
      - CASSANDRA_REPLICATION_FACTOR=1
      - TEMPORAL_CLI_ADDRESS=temporal-frontend:7233
    command: >
      sh -c "
        sleep 30 &&
        temporal-cassandra-tool --endpoints cassandra create -k temporal --replication-factor 1 &&
        temporal-cassandra-tool --endpoints cassandra -k temporal setup-schema -v 0.0 &&
        temporal-cassandra-tool --endpoints cassandra -k temporal update-schema -d /etc/temporal/schema/cassandra/temporal/versioned &&
        temporal-cassandra-tool --endpoints cassandra create -k temporal_visibility --replication-factor 1 &&
        temporal-cassandra-tool --endpoints cassandra -k temporal_visibility setup-schema -v 0.0 &&
        temporal-cassandra-tool --endpoints cassandra -k temporal_visibility update-schema -d /etc/temporal/schema/cassandra/visibility/versioned &&
        sleep infinity
      "
    networks:
      - temporal-network

  # Frontend Service - Client API gateway
  temporal-frontend:
    image: temporalio/server:1.24.2
    container_name: temporal-frontend
    depends_on:
      temporal-admin-tools:
        condition: service_started
    ports:
      - "7233:7233"
      - "7234:7234"
    environment:
      - SERVICES=frontend
      - LOG_LEVEL=info
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamic_config.yaml
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PORT=9042
      - KEYSPACE=temporal
      - VISIBILITY_KEYSPACE=temporal_visibility
      - ES_SEEDS=elasticsearch
      - ES_PORT=9200
      - ES_VERSION=v8
      - PROMETHEUS_ENDPOINT=0.0.0.0:9090
      - NUM_HISTORY_SHARDS=4096
      - TEMPORAL_BROADCAST_ADDRESS=temporal-frontend
    volumes:
      - ./dynamic_config.yaml:/etc/temporal/config/dynamic_config.yaml
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '3'
          memory: 6G
    healthcheck:
      test: ["CMD", "tctl", "--address", "temporal-frontend:7233", "cluster", "health"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - temporal-network

  # History Service - Core workflow execution (scaled to 6 instances)
  temporal-history-1:
    image: temporalio/server:1.24.2
    container_name: temporal-history-1
    depends_on:
      temporal-admin-tools:
        condition: service_started
    environment:
      - SERVICES=history
      - LOG_LEVEL=info
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamic_config.yaml
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PORT=9042
      - KEYSPACE=temporal
      - VISIBILITY_KEYSPACE=temporal_visibility
      - ES_SEEDS=elasticsearch
      - ES_PORT=9200
      - ES_VERSION=v8
      - PROMETHEUS_ENDPOINT=0.0.0.0:9090
      - NUM_HISTORY_SHARDS=4096
      - TEMPORAL_BROADCAST_ADDRESS=temporal-history-1
    volumes:
      - ./dynamic_config.yaml:/etc/temporal/config/dynamic_config.yaml
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 12G
        reservations:
          cpus: '5'
          memory: 10G
    networks:
      - temporal-network

  temporal-history-2:
    image: temporalio/server:1.24.2
    container_name: temporal-history-2
    depends_on:
      temporal-admin-tools:
        condition: service_started
    environment:
      - SERVICES=history
      - LOG_LEVEL=info
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamic_config.yaml
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PORT=9042
      - KEYSPACE=temporal
      - VISIBILITY_KEYSPACE=temporal_visibility
      - ES_SEEDS=elasticsearch
      - ES_PORT=9200
      - ES_VERSION=v8
      - PROMETHEUS_ENDPOINT=0.0.0.0:9090
      - NUM_HISTORY_SHARDS=4096
      - TEMPORAL_BROADCAST_ADDRESS=temporal-history-2
    volumes:
      - ./dynamic_config.yaml:/etc/temporal/config/dynamic_config.yaml
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 12G
        reservations:
          cpus: '5'
          memory: 10G
    networks:
      - temporal-network

  temporal-history-3:
    image: temporalio/server:1.24.2
    container_name: temporal-history-3
    depends_on:
      temporal-admin-tools:
        condition: service_started
    environment:
      - SERVICES=history
      - LOG_LEVEL=info
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamic_config.yaml
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PORT=9042
      - KEYSPACE=temporal
      - VISIBILITY_KEYSPACE=temporal_visibility
      - ES_SEEDS=elasticsearch
      - ES_PORT=9200
      - ES_VERSION=v8
      - PROMETHEUS_ENDPOINT=0.0.0.0:9090
      - NUM_HISTORY_SHARDS=4096
      - TEMPORAL_BROADCAST_ADDRESS=temporal-history-3
    volumes:
      - ./dynamic_config.yaml:/etc/temporal/config/dynamic_config.yaml
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 12G
        reservations:
          cpus: '5'
          memory: 10G
    networks:
      - temporal-network

  temporal-history-4:
    image: temporalio/server:1.24.2
    container_name: temporal-history-4
    depends_on:
      temporal-admin-tools:
        condition: service_started
    environment:
      - SERVICES=history
      - LOG_LEVEL=info
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamic_config.yaml
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PORT=9042
      - KEYSPACE=temporal
      - VISIBILITY_KEYSPACE=temporal_visibility
      - ES_SEEDS=elasticsearch
      - ES_PORT=9200
      - ES_VERSION=v8
      - PROMETHEUS_ENDPOINT=0.0.0.0:9090
      - NUM_HISTORY_SHARDS=4096
      - TEMPORAL_BROADCAST_ADDRESS=temporal-history-4
    volumes:
      - ./dynamic_config.yaml:/etc/temporal/config/dynamic_config.yaml
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 12G
        reservations:
          cpus: '5'
          memory: 10G
    networks:
      - temporal-network

  # Matching Service - Task queue management (scaled to 3 instances)
  temporal-matching-1:
    image: temporalio/server:1.24.2
    container_name: temporal-matching-1
    depends_on:
      temporal-admin-tools:
        condition: service_started
    environment:
      - SERVICES=matching
      - LOG_LEVEL=info
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamic_config.yaml
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PORT=9042
      - KEYSPACE=temporal
      - VISIBILITY_KEYSPACE=temporal_visibility
      - ES_SEEDS=elasticsearch
      - ES_PORT=9200
      - ES_VERSION=v8
      - PROMETHEUS_ENDPOINT=0.0.0.0:9090
      - NUM_HISTORY_SHARDS=4096
      - TEMPORAL_BROADCAST_ADDRESS=temporal-matching-1
    volumes:
      - ./dynamic_config.yaml:/etc/temporal/config/dynamic_config.yaml
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '3'
          memory: 6G
    networks:
      - temporal-network

  temporal-matching-2:
    image: temporalio/server:1.24.2
    container_name: temporal-matching-2
    depends_on:
      temporal-admin-tools:
        condition: service_started
    environment:
      - SERVICES=matching
      - LOG_LEVEL=info
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamic_config.yaml
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PORT=9042
      - KEYSPACE=temporal
      - VISIBILITY_KEYSPACE=temporal_visibility
      - ES_SEEDS=elasticsearch
      - ES_PORT=9200
      - ES_VERSION=v8
      - PROMETHEUS_ENDPOINT=0.0.0.0:9090
      - NUM_HISTORY_SHARDS=4096
      - TEMPORAL_BROADCAST_ADDRESS=temporal-matching-2
    volumes:
      - ./dynamic_config.yaml:/etc/temporal/config/dynamic_config.yaml
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '3'
          memory: 6G
    networks:
      - temporal-network

  temporal-matching-3:
    image: temporalio/server:1.24.2
    container_name: temporal-matching-3
    depends_on:
      temporal-admin-tools:
        condition: service_started
    environment:
      - SERVICES=matching
      - LOG_LEVEL=info
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamic_config.yaml
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PORT=9042
      - KEYSPACE=temporal
      - VISIBILITY_KEYSPACE=temporal_visibility
      - ES_SEEDS=elasticsearch
      - ES_PORT=9200
      - ES_VERSION=v8
      - PROMETHEUS_ENDPOINT=0.0.0.0:9090
      - NUM_HISTORY_SHARDS=4096
      - TEMPORAL_BROADCAST_ADDRESS=temporal-matching-3
    volumes:
      - ./dynamic_config.yaml:/etc/temporal/config/dynamic_config.yaml
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '3'
          memory: 6G
    networks:
      - temporal-network

  # Worker Service - Internal workflows (scaled to 2 instances)
  temporal-worker-1:
    image: temporalio/server:1.24.2
    container_name: temporal-worker-1
    depends_on:
      temporal-admin-tools:
        condition: service_started
    environment:
      - SERVICES=worker
      - LOG_LEVEL=info
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamic_config.yaml
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PORT=9042
      - KEYSPACE=temporal
      - VISIBILITY_KEYSPACE=temporal_visibility
      - ES_SEEDS=elasticsearch
      - ES_PORT=9200
      - ES_VERSION=v8
      - PROMETHEUS_ENDPOINT=0.0.0.0:9090
      - NUM_HISTORY_SHARDS=4096
      - TEMPORAL_BROADCAST_ADDRESS=temporal-worker-1
    volumes:
      - ./dynamic_config.yaml:/etc/temporal/config/dynamic_config.yaml
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 3G
    networks:
      - temporal-network

  temporal-worker-2:
    image: temporalio/server:1.24.2
    container_name: temporal-worker-2
    depends_on:
      temporal-admin-tools:
        condition: service_started
    environment:
      - SERVICES=worker
      - LOG_LEVEL=info
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamic_config.yaml
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PORT=9042
      - KEYSPACE=temporal
      - VISIBILITY_KEYSPACE=temporal_visibility
      - ES_SEEDS=elasticsearch
      - ES_PORT=9200
      - ES_VERSION=v8
      - PROMETHEUS_ENDPOINT=0.0.0.0:9090
      - NUM_HISTORY_SHARDS=4096
      - TEMPORAL_BROADCAST_ADDRESS=temporal-worker-2
    volumes:
      - ./dynamic_config.yaml:/etc/temporal/config/dynamic_config.yaml
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 3G
    networks:
      - temporal-network

  # Prometheus - Metrics collection
  prometheus:
    image: prom/prometheus:v2.48.1
    container_name: temporal-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    networks:
      - temporal-network

  # Grafana - Visualization
  grafana:
    image: grafana/grafana:10.2.3
    container_name: temporal-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on:
      - prometheus
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    networks:
      - temporal-network

  # Temporal Web UI
  temporal-ui:
    image: temporalio/ui:2.22.3
    container_name: temporal-ui
    depends_on:
      temporal-frontend:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal-frontend:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      - temporal-network

volumes:
  cassandra-data:
  elasticsearch-data:
  prometheus-data:
  grafana-data:

networks:
  temporal-network:
    driver: bridge