# prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'temporal-loadtest'
    replica: '1'

scrape_configs:
  - job_name: 'temporal-frontend'
    static_configs:
      - targets: ['temporal-frontend:9090']
        labels:
          service: 'frontend'

  - job_name: 'temporal-history-1'
    static_configs:
      - targets: ['temporal-history-1:9090']
        labels:
          service: 'history'
          instance: '1'

  - job_name: 'temporal-history-2'
    static_configs:
      - targets: ['temporal-history-2:9090']
        labels:
          service: 'history'
          instance: '2'

  - job_name: 'temporal-history-3'
    static_configs:
      - targets: ['temporal-history-3:9090']
        labels:
          service: 'history'
          instance: '3'

  - job_name: 'temporal-matching-1'
    static_configs:
      - targets: ['temporal-matching-1:9090']
        labels:
          service: 'matching'
          instance: '1'

  - job_name: 'temporal-matching-2'
    static_configs:
      - targets: ['temporal-matching-2:9090']
        labels:
          service: 'matching'
          instance: '2'

  - job_name: 'temporal-worker'
    static_configs:
      - targets: ['temporal-worker:9090']
        labels:
          service: 'worker'

  - job_name: 'cassandra'
    static_configs:
      - targets: ['cassandra:9042']
        labels:
          service: 'cassandra'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']